{{ if or (eq .Values.operatorMode "standard") (eq .Values.operatorMode "admin") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ if eq .Values.operatorMode "admin" }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    name: {{ include "litmus.name" . }}-admin
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "litmus.fullname" . }}-admin
subjects:
- kind: ServiceAccount
  name: {{ include "litmus.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ if .Values.litmusPortal.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-rb
  labels:
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
subjects:
  - kind: ServiceAccount
    name: litmus-svc-account
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}
