apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name }}
    chart: {{ include "litmus.chart" . }}
{{ if eq .Values.operatorMode "admin" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    name: {{ include "litmus.name" . }}-admin
    instance: {{ .Release.Name }}
    chart: {{ include "litmus.chart" . }}
{{ end }}
{{ if .Values.litmusPortal.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-svc-account
  labels:
    name: litmus-svc-account
    instance: {{ .Release.Name }}
    chart: {{ include "litmus.chart" . }}
{{ end }}
