# Default values for raas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "raas"
fullnameOverride: "raas"

operatorName: "chaos-operator"

replicaCount: 1

operator:
  image:
    repository: litmuschaos/chaos-operator
    tag: 1.4.0
    pullPolicy: Always
runner:
  image:
    repository: litmuschaos/chaos-runner
    tag: 1.4.0

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host:
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Support for https://docs.litmuschaos.io/docs/admin-mode
administratorMode:
  enabled: false

# Support for disabling google analytics
# https://docs.litmuschaos.io/docs/faq-general/#does-litmus-track-any-usage-metrics-on-the-test-clusters
policies:
  monitoring:
    disabled: false

exporter:
  enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels: {}
  image:
    repository: litmuschaos/chaos-exporter
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

litmusPortal:
  enabled: true

litmusPortalFrontend:
  deployment:
    image:
      repository: litmuschaos/litmusportal-frontend
      tag: ci
      pullPolicy: Always
    containerPort: 80
  service:
    type: NodePort
    port: 9091
    targetPort: 80

litmusPortalServer:
  deployment:
    graphqlServer:
      image:
        repository: litmuschaos/litmusportal-server
        tag: ci
        pullPolicy: Always
      containerPort: 8080
    authServer:
      image:
        repository: litmuschaos/litmusportal-auth-server
        tag: ci
        pullPolicy: Always
      containerPort: 3000
  service:
    type: NodePort
    graphqlServer:
      port: 9002
      targetPort: 8080
    authServer:
      port: 9003
      targetPort: 3000
    
mongoDB:
  deployment:
    image:
      repository: mongo
      tag: "4.2.8"
      pullPolicy: Always
    containerPort: 27017
    mountPath: "/data/db"
    claimName: "mongo-pv-claim"
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017
